version: '3.6'

services:
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
  mb:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
