spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:master-changelog.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
